Repository hotosm/oeg-reporter, pull requests merged in 2020-08, with the labels that each got.

#9 add gh action to test
  .github/workflows/python-app.yml
Labels: Status: Review needed

#11 Add BSD-2 license
  LICENSE.txt
Labels: Priority: High, Status: Review needed

#6 Add git report
  .gitignore
  .gitmodules
  README.md
  docs/git-repository-setup.md
  docs/imgs/communication_diagram.png
  docs/mediawiki-instance-setup.md
  docs/setup-development.md
  example.env
  manage.py
  requirements.txt
  server/__init__.py
  server/api/git/resources.py
  server/config.py
  server/services/git/file_service.py
  server/services/git/git_service.py
  server/tests/base_test_config.py
  server/tests/config/test_app_config.py
  server/tests/helpers/utils.py
  server/tests/models/serializers/test_document.py
  server/tests/models/serializers/test_organisation.py
  server/tests/models/serializers/test_platform.py
  server/tests/models/serializers/test_project.py
  server/tests/services/__init__.py
  server/tests/services/git/__init__.py
  server/tests/services/git/test_file_service.py
  server/tests/services/git/test_git_api.py
  server/tests/services/git/test_git_service.py
Labels: Status: Review needed

#8 Add mediawiki instance report
  .gitignore
  docker-compose.yml
  docs/git-repository-setup.md
  docs/mediawiki-instance-setup.md
  docs/setup-development.md
  example.env
  requirements.txt
  scripts/docker/Dockerfile
  server/__init__.py
  server/api/git/resources.py
  server/api/wiki/__init__.py
  server/api/wiki/resources.py
  server/config.py
  server/models/serializers/document.py
  server/models/serializers/project.py
  server/services/git/file_service.py
  server/services/utils.py
  server/services/wiki/__init__.py
  server/services/wiki/mediawiki_service.py
  server/services/wiki/pages/organisation_service.py
  server/services/wiki/pages/overview_service.py
  server/services/wiki/pages/page_service.py
  server/services/wiki/pages/project_service.py
  server/services/wiki/pages/templates.py
  server/services/wiki/pages/utils.py
  server/services/wiki/wiki_section_service.py
  server/services/wiki/wiki_table_service.py
  server/services/wiki/wiki_text_service.py
  server/tests/helpers/utils.py
  server/tests/services/git/test_git_api.py
  server/tests/services/git/test_git_service.py
  server/tests/services/test_utils.py
  server/tests/services/wiki/__init__.py
  server/tests/services/wiki/pages/__init__.py
  server/tests/services/wiki/pages/test_organisation_service.py
  server/tests/services/wiki/pages/test_overview_service.py
  server/tests/services/wiki/pages/test_project_service.py
  server/tests/services/wiki/pages/test_utils.py
  server/tests/services/wiki/test_mediawiki_service.py
  server/tests/services/wiki/test_wiki_api.py
  server/tests/services/wiki/test_wiki_section_service.py
  server/tests/services/wiki/test_wiki_table_service.py
  server/tests/services/wiki/test_wiki_text_service.py
Labels: Priority: High, Status: In Progress, Status: Review needed
